# Autostart

exec-once = nohup waybar
exec-once = waypaper --restore # Wallpaper and Waybar
exec-once = udiskie # Manage removable media like flash drives

exec-once = hyprsunset -t 5500
exec-once = hyprctl setcursor Bibata-Modern-Classic 24 
